<?php

use App\Build;
use App\Hero;
use App\Map;
use App\User;
use Illuminate\Database\Seeder;

class BuildSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        for($i = 0; $i < 50; $i++) {
            $build = new Build;
            $build->user_id = rand(1,3);

            //this list dont have missing images...
            $hero = Hero::whereIn('id', [1,3,4,6,9,11,13,14,16,17,18,21,22,23,24,25,27,29,32,34,37,39,41,42,43,44,46,47,48,50,51,52,53,54,56,58,60,63,64,65,66,67,68])->inRandomOrder()->first();

            $build->fill([
                'title' => 'First builds of the application!',
                'description' => 'i was generated by a seeder :)',
            ]);

            $build->hero_id = $hero->id;
            $build->save();

            $hero->talents = $hero->talents()->orderBy('id')->get()->groupBy('level');

            foreach($hero->talents as $level => $talents){
                $build->talents()->attach($talents->random());
            }

            $maps = Map::inRandomOrder()->limit(rand(1,5))->get();

            foreach($maps as $map){
                $build->maps()->attach($map);
            }
        }
    }
}
