<?php

use App\Build;
use App\Hero;
use App\User;
use Illuminate\Database\Seeder;

class BuildSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        for($i = 0; $i < 10; $i++){
            $build = new Build;
            $build->user_id = rand(1,3);

            $hero = Hero::inRandomOrder()->first();

            $build->fill([
                'title' => 'First builds of the application!',
                'description' => 'i was generated by a seeder :)',
            ]);

            $build->hero_id = $hero->id;
            $build->save();

            $hero->talents = $hero->talents()->orderBy('id')->get()->groupBy('level');

            foreach($hero->talents as $level => $talents){
                $build->talents()->attach($talents->random());
            }
        }
    }
}
